name: ci
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.13.2
      - run: dart analyze
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart run test/all.dart
      - run: dart --enable-asserts run test/all.dart
